name: Versions
version: 1.1.4
description: Receive a notification when there's a new version of Statamic or any of your addons
url: https://github.com/edalzell/statamic-versions
developer: Erin Dalzell
developer_url: https://github.com/edalzell/
